ARG NODE_VERSION="22.14.0"
ARG PNPM_VERSION="8.15.8"

##
# Create base image with pnpm installed 
##

FROM node:${NODE_VERSION}-alpine as thanhlq-pnpm
LABEL thanhlq/web3.name=pnpm

RUN apk add git
RUN apk add --no-cache --upgrade grep
RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
  npm i -g pnpm@${PNPM_VERSION}

WORKDIR /app

COPY ["./*.json", "./*.yaml", "./"]
